### ISSUE TITLE
Predefined template properties

### ISSUE THREAD

**Issue by sielay** [getlackey/lackey-cms#6]
# Predefined template properties

## Type

 * Feature Request
* Documentation

## Expected behaviour

Should predefine (restrict) following properties for top level context
```
og_title
og_type
og_description
og_image
```
 * `og_type` should have default value set in template
 * `og_image` should be connected to gallery

For `<title>` and `<meta type="description">` tags og values should be used (guideline).

**Comment by sielay** [comment]
Deployed with d71795a6b409174e2ac4131768c6d1a83c81baa9

**Comment by sielay** [comment]
Example of overidding/setting default value in `Content` declaration
```yaml
props:
            og_type:
                label: Type
                default: Article
                name: og_type
```
